version: '3'

services:
  sanafi-launchpad:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - '3012:3012'
    environment:
      - NODE_ENV=production
      - PORT=3012
      # Add your environment variables here
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_BUCKET=${R2_BUCKET}
      - RPC_URL=${RPC_URL}
      - NEXT_PUBLIC_POOL_CONFIG_KEY=${NEXT_PUBLIC_POOL_CONFIG_KEY}
    restart: always
